### ISSUE TITLE
Update the "Who We Are" page

### ISSUE THREAD

**Issue by jakelever** [hackseq/hackseq_2017#13]
Hey, we should update the Who We Are page (http://www.hackseq.com/who-we-are/). Maybe put up our photos and keep the names of hackseq 2016 people?

I guess everyone should send photos, a few words and a URL to @jasgrewal . Is that alright?

**Comment by lfunderburk** [comment]
Please send photos and I will be happy to add them to the website.

**Comment by lfunderburk** [comment]
I think also adding an intro would help. Sorry everyone for being disconnected lately. I have been adjusting to change, sorting out bureaucracy and fighting jet-lag. I am back on track and will be happy to lend a hand where is help is needed. I need clarification regarding web/graphic design designation. Last time I volunteered but because I have not been attending the meeting and have been out of the loop a bit I am not sure if tasks were reassigned. I am still happy to help on this and will be glad to pair up if someone took over. 

This might be a question whose answer is obvious to you: where can I find the meeting minutes?

Also... I have been learning German and for some reason it is scrambling my English in unpredictable ways. Please feel free to point out my mistakes... specially when done on the page.

**Comment by jakelever** [comment]
@lfunderburk glad to hear that you're settling into life in Germany. Meeting minutes can be found at: https://github.com/hackseq/hackseq_2017/tree/master/organization/meeting_minutes

**Comment by dfornika** [comment]
@lfunderburk I've uploaded a photo of myself to the 'website' directory of the private repo.

**Comment by jasgrewal** [comment]
@lfunderburk @jakelever I had some time to spare over lunch so I've started a new stub of 'who we are' which is not currently directly accessible through the website. We can link it to the real dealio once all the team pics are uploaded to website/team_photos in the private repo. @lfunderburk you can find the current stub page under Secondary Navigation, if you plan to edit/upload the rest :)
@dfornika I've moved your photo over to the team pics dir ^_^

**Comment by jasgrewal** [comment]
Hi team, if everyone can update the README with their deets with the following format: [Name](website) / affiliation / [Twitter Handle? Gmail account?](https://twitter.com/ or gmail address)

**Comment by csiu** [comment]
@jasgrewal I've uploaded my picture
