### ISSUE TITLE
slack channel

### ISSUE THREAD

**Issue by lchong** [hackseq/hackseq_2017#32]
Hi @sjackman,

I understand that we had a slack channel set up for last year's hackseq. Can you give me the info about what email it's attached to? I'm wondering if we can use the same channel for this year's event.

Thanks!

**Comment by sjackman** [comment]
The Slack channel is https://hackseq.slack.com
I've invited you. Once you're in, I'll make you an admin.

**Comment by sjackman** [comment]
Last year we had the trouble that if you invite too many people all at once, and not enough of those people accept the invitation, so that you have a bunch of outstanding invites, you get throttled, and you won't be able to invite any more people. That's just to say invite the participants to Slack early enough that if this happens again, you have time to sort it out with Slack support.

**Comment by lchong** [comment]
Great, thank you!

**Comment by sjackman** [comment]
You're an owner now!

**Comment by rdocking** [comment]
Can I get an invite as well? One of my team members has asked about this - I'd prefer to use the group channel.

**Comment by sjackman** [comment]
Done!

**Comment by rdocking** [comment]
Thanks Shaun! Could you also invite @hiraksarkar ?

**Comment by sjackman** [comment]
Done!
